---
title: "2_graphics_skillsgap"
author: "Lisa Pramann"
date: "14 3 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("98_packages.R")
source("1_data_wrangling.R")
```

1. Manufacturing export-led growth regimes sectoral skills gap

```{r}
manufactoring_data <- OECD_data_raw %>% 
  filter(Country == c("Germany", "Austria"))


ggplot(subset(OECD_data_raw,Country == c("Germany", "Austria")),
       aes(x=Skills, y=Value, fill = factor(Industry))) + 
  geom_bar(stat = "identity", position = "dodge") +
  coord_flip() +
  theme_minimal() +
  scale_fill_discrete(name="Industry",
                      labels=c("ICT", "Manufacturing")) +
  facet_wrap(~Country)


```

2. Dynamic Services export-led growth regimes sectoral skills gap

```{r}
#den <-
  ggplot(subset(OECD_data_raw,Country == c("Denmark")),
       aes(x=Skills, y=Value, fill = factor(Industry))) + 
  geom_bar(stat = "identity", position = "dodge") +
  coord_flip() +
  theme_minimal() +
  scale_fill_discrete(name="Industry",
                      labels=c("ICT", "Manufacturing"))

#swe <- 
  ggplot(subset(OECD_data_raw,Country == c("Sweden")),
       aes(x=Skills, y=Value, fill = factor(Industry))) + 
  geom_bar(stat = "identity", position = "dodge") +
  coord_flip() +
  theme_minimal() +
  scale_fill_discrete(name="Industry",
                      labels=c("ICT", "Manufacturing"))

#nor <- 
  ggplot(subset(OECD_data_raw,Country == c("Norway")),
       aes(x=Skills, y=Value, fill = factor(Industry))) + 
  geom_bar(stat = "identity", position = "dodge") +
  coord_flip() +
  theme_minimal() +
  scale_fill_discrete(name="Industry",
                      labels=c("ICT", "Manufacturing"))

facet_grid(den, swe, nor)


# Default with no hjust
ggarrange(den, swe, nor + rremove("ylab"), labels  = "Denmark", "Seweden", "Norway") 

```





